# This is a generated file. Not intended for manual editing.
services:
  animalhealth.api:
    build:
      context: "C:\\Users\\xefheh\\RiderProjects\\AnimalHealth"
      dockerfile: "AnimalHealth.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/AnimalHealth.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\xefheh\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\xefheh\\.nuget\\packages"
    image: "animalhealth.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\xefheh\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\xefheh\\RiderProjects\\AnimalHealth\\AnimalHealth.API:/app:rw"
    - "C:\\Users\\xefheh\\RiderProjects\\AnimalHealth:/src:rw"
    working_dir: "/app"
